import os
import re

VALID_DOMAINS_FILE = "/home/kdos/Anvil/kdos-main/tools/valid-domains.txt"
CONTENT_DIR = "/home/kdos/Anvil/kdos-main/content/knowledge"

def load_valid_domains():
    with open(VALID_DOMAINS_FILE, 'r') as f:
        # Read lines and strip whitespace
        return set(line.strip() for line in f if line.strip())

def process_file(filepath, valid_domains):
    with open(filepath, 'r') as f:
        content = f.read()

    # Regex to find the domains list in frontmatter
    # Looks for 'domains: [...]' or multi-line list
    # This simple regex assumes the format generated by the agent: domains: ["A", "B"]
    match = re.search(r'^domains:\s*\[(.*?)\]', content, re.MULTILINE)
    
    if not match:
        # Try to find list format if not inline array
        # But based on previous generation, it's likely ["A", "B"]
        return False

    original_domains_str = match.group(1)
    # Parse the list items
    # Extract strings between quotes
    current_domains = [d.strip().strip('"\'') for d in original_domains_str.split(',')]
    current_domains = [d for d in current_domains if d] # Remove empty strings

    # Filter domains
    new_domains = []
    has_changes = False
    
    for domain in current_domains:
        if domain in valid_domains:
            new_domains.append(domain)
        else:
            print(f"Removing invalid domain '{domain}' from {filepath}")
            has_changes = True
            
    if has_changes:
        # Reconstruct the line
        new_domains_str = ', '.join([f'"{d}"' for d in new_domains])
        new_line = f'domains: [{new_domains_str}]'
        
        # Replace in content
        # We need to be careful to replace only the specific matched line
        # The match object gives us the span of the inner content, but we want the whole line
        # Let's replace the whole match
        
        full_match = match.group(0)
        new_content = content.replace(full_match, new_line)
        
        with open(filepath, 'w') as f:
            f.write(new_content)
        return True
    
    return False

def main():
    valid_domains = load_valid_domains()
    print(f"Loaded {len(valid_domains)} valid domains.")
    
    count = 0
    for root, dirs, files in os.walk(CONTENT_DIR):
        for file in files:
            if file.endswith(".md"):
                filepath = os.path.join(root, file)
                if process_file(filepath, valid_domains):
                    count += 1
                    
    print(f"Updated {count} files.")

if __name__ == "__main__":
    main()
